
server:
  port: 8090
  error:
    include-message: always

spring:
  application:
    name: email-sender-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: baskaranthangam98
    password: gpnb inou hkpn pxhb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

