
server:
  port: 8082
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kanban_db
  application:
    name: kanban-service

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
      fetchRegistry: true
      registerWithEureka: true

